' CST Parameter Update Macro - Generated by AutoDesign
'
Sub Main()
    Dim proj As Object
    Set proj = GetProject()

    ' Update parameters
    proj.StoreDoubleParameter "patch_length", 12.0
    proj.StoreDoubleParameter "patch_width", 10.0

    ' Rebuild the model
    proj.Rebuild

    MsgBox "Parameters updated successfully!"
End Sub