"""
CST 文件交换控制器
通过文件与 CST 进行数据交换，避免 COM 接口问题
"""

import json
import time
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
import os


class CSTFileController:
    """
    通过文件与 CST 交换数据的控制器

    工作流程：
    1. 生成参数更新 VBA 宏文件
    2. 生成仿真控制脚本
    3. 导出 S11 数据到文件
    4. 读取 S11 文件
    """

    def __init__(self, cst_exe_path: Optional[str] = None, project_path: Optional[str] = None):
        self.cst_exe_path = cst_exe_path or self._find_cst_exe()
        self.project_path = project_path
        self.work_dir = Path("outputs/cst_work")
        self.work_dir.mkdir(parents=True, exist_ok=True)

    def _find_cst_exe(self) -> str:
        """自动查找 CST 安装路径"""
        common_paths = [
            r"D:\Program Files (x86)\CST Studio Suite 2024\CST DESIGN ENVIRONMENT.exe",
            r"C:\Program Files (x86)\CST Studio Suite 2024\CST DESIGN ENVIRONMENT.exe",
            r"D:\CST Studio Suite 2024\CST DESIGN ENVIRONMENT.exe",
            r"C:\CST Studio Suite 2024\CST DESIGN ENVIRONMENT.exe",
        ]
        for path in common_paths:
            if Path(path).exists():
                return path
        return ""

    def connect(self) -> bool:
        """检查 CST 是否可访问"""
        print("[FileController] Ready to use")
        return True

    def open_project(self, project_path: str) -> bool:
        """
        记录项目路径

        在文件模式下，假设用户已在 CST 中打开项目
        """
        abs_path = Path(project_path).resolve()
        if abs_path.exists():
            self.project_path = str(abs_path)
            print(f"[FileController] Project path: {self.project_path}")
            print("[FileController] Please ensure this project is open in CST")
            return True
        else:
            print(f"[Warning] Project path not found: {abs_path}")
            print("[FileController] Please manually open the project in CST")
            # 仍然返回 True，因为用户可以在 CST 中手动打开
            return True

    def generate_param_macro(self, params: Dict[str, float]) -> str:
        """生成参数更新 VBA 宏"""
        macro_file = self.work_dir / "update_params.mcr"

        lines = [
            "' CST Parameter Update Macro - Generated by AutoDesign",
            "'",
            "Sub Main()",
            "    Dim proj As Object",
            "    Set proj = GetProject()",
            "",
            "    ' Update parameters",
        ]

        # 只添加数值型参数（过滤特殊键）
        for name, value in params.items():
            # 跳过非数值参数
            if name.startswith("_") or name in ["project_path", "targets", "auto_design", "max_iterations"]:
                continue
            # 确保值是数值类型
            if isinstance(value, (int, float)):
                lines.append(f'    proj.StoreDoubleParameter "{name}", {value}')

        lines.extend([
            "",
            "    ' Rebuild the model",
            "    proj.Rebuild",
            "",
            "    MsgBox \"Parameters updated successfully!\"",
            "End Sub",
        ])

        macro_file.write_text("\n".join(lines), encoding="utf-8")
        print(f"[FileController] Generated macro: {macro_file}")
        return str(macro_file)

    def generate_export_s11_macro(self, export_path: str) -> str:
        """生成导出 S11 的 VBA 宏"""
        macro_file = self.work_dir / "export_s11.mcr"

        # 转换路径分隔符为双反斜杠（VBA 需要）
        vba_path = export_path.replace("\\", "\\\\")

        lines = [
            "' CST S11 Export Macro - Generated by AutoDesign",
            "'",
            "Sub Main()",
            "    Dim proj As Object",
            "    Dim results As Object",
            "    Dim s11_result As Object",
            "",
            f'    Dim exportPath As String',
            f'    exportPath = "{vba_path}"',
            "",
            "    Set proj = GetProject()",
            "    Set results = proj.GetResultsInTree()",
            "",
            "    ' Find and export S11",
            "    Dim i As Integer",
            "    For i = 0 To results.Count - 1",
            "        Dim item As Object",
            "        Set item = results.Item(i)",
            "        Dim itemName As String",
            "        itemName = item.GetName()",
            "",
            "        If InStr(itemName, \"S1,1\") > 0 Or InStr(itemName, \"S11\") > 0 Then",
            "            ' Export to ASCII",
            "            item.ExportCurve \"default\", exportPath, True",
            "            MsgBox \"S11 exported to: \" & exportPath",
            "            Exit Sub",
            "        End If",
            "    Next",
            "",
            "    MsgBox \"S11 result not found!\"",
            "End Sub",
        ]

        macro_file.write_text("\n".join(lines), encoding="utf-8")
        print(f"[FileController] Generated export macro: {macro_file}")
        return str(macro_file)

    def set_parameters(self, params: Dict[str, float]) -> bool:
        """
        设置参数 - 生成 VBA 宏文件

        用户需要：
        1. 在 CST 中打开项目
        2. 通过 Macros -> Import 导入生成的宏文件
        3. 运行宏更新参数
        """
        macro_file = self.generate_param_macro(params)

        print("\n" + "="*60)
        print("IMPORTANT: Manual action required in CST")
        print("="*60)
        print(f"1. Go to CST: Macros -> Import -> Select: {macro_file}")
        print("2. Run the macro to update parameters")
        print("3. Run simulation manually")
        print("4. After simulation, export S11 or continue")
        print("="*60 + "\n")

        # 生成一个批处理文件来自动执行（可选）
        self._generate_cst_automation_script(params)

        return True

    def _generate_cst_automation_script(self, params: Dict[str, float]):
        """生成 Python 自动化脚本供 CST 使用"""
        script_file = self.work_dir / "cst_automation.py"

        script_content = f'''"""
CST Automation Script
Run this in CST's Python environment
"""

import cst

# Get current project
proj = cst.project

# Update parameters
'''
        for name, value in params.items():
            script_content += f'proj.set_parameter("{name}", {value})\n'

        script_content += '''
# Rebuild
proj.rebuild()

# Run simulation
solver = proj.get_solver()
solver.run()

print("Simulation completed!")
'''

        script_file.write_text(script_content, encoding="utf-8")
        print(f"[FileController] Generated Python script: {script_file}")

    def run_simulation(self, wait_complete: bool = True, timeout: int = 600) -> bool:
        """
        运行仿真 - 通过生成脚本

        注意：由于 COM 接口限制，需要用户在 CST 中手动运行仿真
        """
        print("\n" + "="*60)
        print("IMPORTANT: Run simulation in CST")
        print("="*60)
        print("Please run the simulation manually in CST:")
        print("1. Click 'Home' -> 'Start Simulation'")
        print("   OR press F5")
        print("2. Wait for simulation to complete")
        print("3. Press Enter here to continue...")
        print("="*60 + "\n")

        if wait_complete:
            input("Press Enter after simulation completes...")

        return True

    def get_s11_parameters(self) -> Dict[str, Any]:
        """
        读取 S11 参数

        尝试多种方式：
        1. 从导出的 ASCII 文件读取
        2. 如果文件不存在，提示用户导出
        """
        # 尝试读取已有的导出文件
        s11_file = self.work_dir / "s11_export.txt"

        if s11_file.exists():
            return self._parse_s11_file(str(s11_file))

        # 生成导出宏
        export_file = self.work_dir / "s11_data.txt"
        self.generate_export_s11_macro(str(export_file))

        print("\n" + "="*60)
        print("IMPORTANT: Export S11 from CST")
        print("="*60)
        print(f"1. In CST, run the export macro: {self.work_dir / 'export_s11.mcr'}")
        print(f"2. Or export S11 to: {export_file}")
        print("3. After exporting, press Enter to continue...")
        print("="*60 + "\n")

        input("Press Enter after exporting S11...")

        # 尝试读取导出的文件
        if export_file.exists():
            return self._parse_s11_file(str(export_file))

        # 如果还是没有，返回错误
        return {
            "success": False,
            "message": "S11 data file not found. Please export S11 from CST.",
            "frequencies_GHz": [],
            "s11_dB": [],
        }

    def _parse_s11_file(self, file_path: str) -> Dict[str, Any]:
        """解析 S11 ASCII 文件"""
        freqs = []
        s11_db = []

        try:
            with open(file_path, "r") as f:
                for line in f:
                    line = line.strip()
                    # Skip comments and empty lines
                    if not line or line.startswith("#") or line.startswith("!"):
                        continue

                    parts = line.split()
                    if len(parts) >= 2:
                        try:
                            freq = float(parts[0])
                            s11 = float(parts[1])
                            freqs.append(freq)
                            s11_db.append(s11)
                        except ValueError:
                            continue

            if not freqs:
                return {
                    "success": False,
                    "message": "No valid data in S11 file",
                    "frequencies_GHz": [],
                    "s11_dB": [],
                }

            # Calculate metrics
            min_idx = s11_db.index(min(s11_db))
            s11_min = s11_db[min_idx]
            freq_at_min = freqs[min_idx]

            # Calculate 10dB bandwidth
            within_10db = [f for f, s in zip(freqs, s11_db) if s <= -10.0]
            bandwidth = (max(within_10db) - min(within_10db)) * 1000 if within_10db else 0.0

            return {
                "success": True,
                "message": "S11 data loaded from file",
                "frequencies_GHz": freqs,
                "s11_dB": s11_db,
                "s11_min_dB": round(s11_min, 3),
                "freq_at_min_GHz": round(freq_at_min, 3),
                "bandwidth_10dB_MHz": round(bandwidth, 1),
            }

        except Exception as e:
            return {
                "success": False,
                "message": f"Error reading S11 file: {e}",
                "frequencies_GHz": [],
                "s11_dB": [],
            }

    def save_project(self, new_path: Optional[str] = None) -> bool:
        """提示用户保存项目"""
        if new_path:
            print(f"\n[FileController] Please save project to: {new_path}")
            print("In CST: File -> Save As -> Select the path")
        else:
            print("\n[FileController] Please save project in CST")
        return True

    def close(self):
        """清理工作目录"""
        print("\n[FileController] Work files saved in:", self.work_dir)


# 为了保持兼容性，引入 FakeCSTController
from scripts.cst_controller import FakeCSTController
