"""
CST Batch Controller - Fixed Version with better error handling
"""

import json
import subprocess
import time
from pathlib import Path
from typing import Any, Dict, List, Optional
import os


class CSTBatchController:
    """
    Fully automated CST controller with diagnostics
    """

    def __init__(self, cst_install_path: Optional[str] = None):
        self.cst_install_path = cst_install_path or self._find_cst_install()
        self.cst_exe = Path(self.cst_install_path) / "CST DESIGN ENVIRONMENT.exe"
        self.work_dir = Path("outputs/cst_batch")
        self.work_dir.mkdir(parents=True, exist_ok=True)
        self.current_iteration = 0
        self.cst_process = None
        self._last_export_path = None

    def _find_cst_install(self) -> str:
        """Find CST installation"""
        common_paths = [
            r"D:\Program Files (x86)\CST Studio Suite 2024",
            r"C:\Program Files (x86)\CST Studio Suite 2024",
        ]
        for path in common_paths:
            if Path(path).exists():
                return path
        raise FileNotFoundError("CST not found")

    def connect(self) -> bool:
        """Check CST executable"""
        if not self.cst_exe.exists():
            print(f"[Batch] CST not found: {self.cst_exe}")
            return False
        print(f"[Batch] CST found: {self.cst_exe}")
        return True

    def open_project(self, project_path: str) -> bool:
        """Record project path"""
        abs_path = Path(project_path).resolve()
        if abs_path.exists():
            self.project_path = str(abs_path)
            print(f"[Batch] Project: {self.project_path}")
            return True
        return False

    def set_parameters(self, params: Dict[str, float]) -> bool:
        """Generate and launch batch script"""
        self.current_iteration += 1
        iter_num = self.current_iteration

        export_file = self.work_dir / f"s11_iter_{iter_num}.txt"
        self._last_export_path = str(export_file)

        macro_file, batch_file = self._generate_files(params, str(export_file), iter_num)

        print(f"\n[Batch] Generated:")
        print(f"  Macro: {macro_file}")
        print(f"  Batch: {batch_file}")
        print(f"  Expected S11: {export_file}")

        # Launch batch script
        print(f"\n[Batch] Launching CST...")
        try:
            # Use CREATE_NEW_CONSOLE to see CST window
            self.cst_process = subprocess.Popen(
                [str(batch_file)],
                shell=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                creationflags=subprocess.CREATE_NEW_CONSOLE if os.name == 'nt' else 0
            )
            print(f"[Batch] CST started (PID: {self.cst_process.pid})")
            print(f"[Batch] Waiting for macro to complete in CST...")
            return True
        except Exception as e:
            print(f"[Batch] Failed to start: {e}")
            return False

    def _generate_files(self, params: Dict[str, float], export_path: str, iter_num: int) -> tuple:
        """Generate macro and batch files"""
        macro_file = self.work_dir / f"auto_run_{iter_num}.mcr"

        # Build parameter code
        param_code = []
        for name, value in params.items():
            if name.startswith("_") or name in ["project_path", "targets"]:
                continue
            if isinstance(value, (int, float)):
                param_code.append(f'    StoreDoubleParameter "{name}", CDbl({value})')

        params_vba = "\n".join(param_code) if param_code else "    ' No parameters"

        # Use absolute path for export
        abs_export_path = str(Path(export_path).resolve())
        vba_export_path = abs_export_path.replace("\\", "\\\\")

        # Improved VBA macro with better error handling
        vba_code = f'''\' CST Auto Run - Iteration {iter_num}
\' Generated by AutoDesign System

Sub Main()
    On Error Resume Next
    
    Dim proj As Object
    Dim solver As Object
    Dim results As Object
    Dim exportSuccess As Boolean
    Dim errorMsg As String
    
    exportSuccess = False
    errorMsg = ""
    
    \' Get project
    Set proj = GetProject()
    If proj Is Nothing Then
        errorMsg = "Cannot get project"
        GoTo Cleanup
    End If
    
    Debug.Print "=== CST Auto Run {iter_num} Started ==="
    
    \' Update parameters
    Debug.Print "Step 1: Updating parameters..."
{params_vba}
    If Err.Number <> 0 Then
        errorMsg = "Parameter update failed: " & Err.Description
        GoTo Cleanup
    End If
    
    \' Rebuild
    Debug.Print "Step 2: Rebuilding model..."
    Err.Clear
    proj.Rebuild
    If Err.Number <> 0 Then
        errorMsg = "Rebuild failed: " & Err.Description
        GoTo Cleanup
    End If
    Debug.Print "Rebuild OK"
    
    \' Run simulation
    Debug.Print "Step 3: Starting simulation..."
    Set solver = proj.GetSolver()
    If solver Is Nothing Then
        errorMsg = "Cannot get solver"
        GoTo Cleanup
    End If
    
    Err.Clear
    solver.Start
    If Err.Number <> 0 Then
        errorMsg = "Solver start failed: " & Err.Description
        GoTo Cleanup
    End If
    
    \' Wait for completion
    Debug.Print "Step 4: Waiting for simulation..."
    Dim simCount As Integer
    simCount = 0
    Do While solver.IsSimulating
        Sleep 2000
        simCount = simCount + 1
        Debug.Print "  Simulating... (" & simCount & "s)"
        If simCount > 1800 Then  \' 1 hour timeout
            errorMsg = "Simulation timeout"
            GoTo Cleanup
        End If
    Loop
    Debug.Print "Simulation completed!"
    
    \' Export S11
    Debug.Print "Step 5: Exporting S11..."
    Set results = proj.GetResultsInTree()
    If results Is Nothing Then
        errorMsg = "No results found"
        GoTo Cleanup
    End If
    
    Debug.Print "Found " & results.Count & " results"
    
    Dim i As Integer
    Dim foundS11 As Boolean
    foundS11 = False
    
    For i = 0 To results.Count - 1
        Dim item As Object
        Set item = results.Item(i)
        If Not item Is Nothing Then
            Dim itemName As String
            itemName = item.GetName()
            Debug.Print "  Checking: " & itemName
            
            \' Try multiple patterns
            If InStr(itemName, "S1,1") > 0 Or _
               InStr(itemName, "S11") > 0 Or _
               InStr(itemName, "S-Parameter") > 0 Or _
               InStr(itemName, "S Parameters") > 0 Then
                
                Debug.Print "  Found S11: " & itemName
                Err.Clear
                item.ExportCurve "default", "{vba_export_path}", True
                
                If Err.Number = 0 Then
                    exportSuccess = True
                    foundS11 = True
                    Debug.Print "  Export OK to: {vba_export_path}"
                Else
                    Debug.Print "  Export failed: " & Err.Description
                End If
                Exit For
            End If
        End If
    Next
    
    If Not foundS11 Then
        errorMsg = "S11 result not found in results tree"
    End If
    
Cleanup:
    \' Always create flag file
    On Error Resume Next
    Dim fso As Object
    Dim flagFile As Object
    Set fso = CreateObject("Scripting.FileSystemObject")
    Set flagFile = fso.CreateTextFile("{vba_export_path}.done", True)
    
    If exportSuccess Then
        flagFile.WriteLine "SUCCESS: Iteration {iter_num} completed"
        flagFile.Close
        MsgBox "Iteration {iter_num} completed successfully!" & vbCrLf & _
               "S11 exported to:" & vbCrLf & "{abs_export_path}", vbInformation
    Else
        flagFile.WriteLine "FAILED: " & errorMsg
        flagFile.Close
        MsgBox "Iteration {iter_num} FAILED:" & vbCrLf & errorMsg & vbCrLf & vbCrLf & _
               "Please check:" & vbCrLf & _
               "1. Is S-Parameter simulation set up?" & vbCrLf & _
               "2. Does the project have valid results?", vbExclamation
    End If
    
    Debug.Print "=== CST Auto Run {iter_num} Finished ==="
End Sub

Sub Sleep(milliseconds As Long)
    Dim endTime As Double
    endTime = Timer + milliseconds / 1000
    Do While Timer < endTime
        DoEvents
    Loop
End Sub
'''

        macro_file.write_text(vba_code, encoding="utf-8")

        # Generate batch file
        batch_file = self.work_dir / f"run_iteration_{iter_num}.bat"
        batch_content = f'''@echo off
echo ==========================================
echo CST Auto Run - Iteration {iter_num}
echo ==========================================
echo.
echo Starting CST with automatic macro execution...
echo.
echo Project: {self.project_path}
echo Macro: {macro_file}
echo.
"{self.cst_exe}" "{self.project_path}" -macro "{macro_file}"
echo.
echo CST session ended.
'''
        batch_file.write_text(batch_content, encoding="utf-8")

        return str(macro_file), str(batch_file)

    def run_simulation(self, wait_complete: bool = True, timeout: int = 600) -> bool:
        """Wait for completion with better diagnostics"""
        if not self.cst_process:
            print("[Batch] No active process")
            return False

        if wait_complete:
            print(f"\n[Batch] Waiting for completion (timeout: {timeout}s)...")
            export_file = Path(self._last_export_path)
            flag_file = Path(str(export_file) + ".done")

            start_time = time.time()
            check_interval = 2
            last_status_time = start_time

            while time.time() - start_time < timeout:
                # Check for completion flag
                if flag_file.exists():
                    try:
                        with open(flag_file, 'r') as f:
                            status = f.read().strip()
                        if "SUCCESS" in status:
                            print(f"[Batch] Completion detected (SUCCESS)")
                            return True
                        elif "FAILED" in status:
                            print(f"[Batch] Completion detected (FAILED)")
                            print(f"[Batch] Check CST window for error message")
                            return False
                    except:
                        pass

                # Check if process exited
                ret = self.cst_process.poll()
                if ret is not None:
                    print(f"[Batch] Process exited with code: {ret}")
                    # Still check if flag file was created
                    if flag_file.exists():
                        return True
                    return False

                time.sleep(check_interval)

                # Print status every 10 seconds
                elapsed = time.time() - start_time
                if time.time() - last_status_time >= 10:
                    print(f"  [Batch] Waiting... ({int(elapsed)}s elapsed)")
                    if export_file.exists():
                        print(f"  [Batch] S11 file exists: {export_file.stat().st_size} bytes")
                    last_status_time = time.time()

            print("[Batch] Timeout reached!")
            return False
        return True

    def get_s11_parameters(self) -> Dict[str, Any]:
        """Read S11 results with better error handling"""
        if not self._last_export_path:
            return {
                "success": False,
                "message": "No export path set",
                "frequencies_GHz": [],
                "s11_dB": [],
            }

        export_file = Path(self._last_export_path)
        flag_file = Path(str(export_file) + ".done")

        print(f"\n[Batch] Looking for S11 file: {export_file}")

        # Wait for file with progress
        max_wait = 60
        for i in range(max_wait):
            if export_file.exists():
                file_size = export_file.stat().st_size
                print(f"[Batch] S11 file found: {file_size} bytes")
                if file_size > 0:
                    break
            if i % 10 == 0 and i > 0:
                print(f"  [Batch] Still waiting... ({i}s)")
            time.sleep(1)

        if not export_file.exists():
            print("[Batch] ERROR: S11 file not generated!")
            print("[Batch] Possible causes:")
            print("  1. CST macro failed to execute")
            print("  2. S-Parameter simulation not set up in project")
            print("  3. Simulation didn't produce S11 results")
            print("  4. Export path issue")

            # Check flag file for error info
            if flag_file.exists():
                try:
                    with open(flag_file, 'r') as f:
                        flag_content = f.read().strip()
                    print(f"[Batch] Flag file content: {flag_content}")
                except:
                    pass

            return {
                "success": False,
                "message": "S11 file not found - check CST window for errors",
                "frequencies_GHz": [],
                "s11_dB": [],
            }

        # Try to parse
        result = self._parse_s11(str(export_file))
        if result["success"]:
            print(f"[Batch] S11 parsed: {result['s11_min_dB']} dB @ {result['freq_at_min_GHz']} GHz")
        else:
            print(f"[Batch] Parse failed: {result['message']}")

        return result

    def _parse_s11(self, file_path: str) -> Dict[str, Any]:
        """Parse S11 file"""
        freqs, s11_db = [], []
        try:
            with open(file_path, "r") as f:
                for line_num, line in enumerate(f, 1):
                    line = line.strip()
                    if not line or line.startswith(("#", "!")):
                        continue
                    parts = line.split()
                    if len(parts) >= 2:
                        try:
                            freq = float(parts[0])
                            s11 = float(parts[1])
                            freqs.append(freq)
                            s11_db.append(s11)
                        except ValueError as e:
                            if line_num <= 5:  # Only show first few parse errors
                                print(f"  [Batch] Parse warning line {line_num}: {e}")
                            continue

            if freqs:
                min_idx = s11_db.index(min(s11_db))
                within_10db = [f for f, s in zip(freqs, s11_db) if s <= -10.0]
                bw = (max(within_10db) - min(within_10db)) * 1000 if within_10db else 0.0
                return {
                    "success": True,
                    "message": "S11 loaded from batch export",
                    "frequencies_GHz": freqs,
                    "s11_dB": s11_db,
                    "s11_min_dB": round(s11_db[min_idx], 3),
                    "freq_at_min_GHz": round(freqs[min_idx], 3),
                    "bandwidth_10dB_MHz": round(bw, 1),
                }
            else:
                return {
                    "success": False,
                    "message": "No valid data points in file",
                    "frequencies_GHz": [],
                    "s11_dB": [],
                }
        except Exception as e:
            return {
                "success": False,
                "message": f"Parse error: {e}",
                "frequencies_GHz": [],
                "s11_dB": [],
            }

    def save_project(self, new_path: Optional[str] = None) -> bool:
        print("[Batch] Please save manually in CST if needed")
        return True

    def close(self):
        if self.cst_process and self.cst_process.poll() is None:
            try:
                self.cst_process.terminate()
            except:
                pass
        print(f"[Batch] Work files: {self.work_dir}")


# Compatibility import
from scripts.cst_controller import FakeCSTController
